In [1]:
Num1 = [20, 30, 10, 50, 7, 8, 3]# Created a list for Num1 value
Num1

[20, 30, 10, 50, 7, 8, 3]

In [2]:
#Scenario 1
max(Num1)#maximum value from the Num1 list
print(Num1)

[20, 30, 10, 50, 7, 8, 3]


In [3]:
#scenario 2
fruits = ["apple", "banana", "cherry"] #List of string
result = ", ".join(fruits)
print(result)


apple, banana, cherry


In [4]:
#scenario 3
ages = {"Alice": 25, "Bob": 30, "Dev": 22, "Eva": 28}
dev_age = ages["Dev"]# Get the age of "Dev"
print(dev_age)


22


In [5]:
#scenario 4
numbers = [1, 2, 2, 3, 4, 4, 5]
unique_numbers = []
for num in numbers:
    if num not in unique_numbers:
        unique_numbers.append(num)
print(unique_numbers)


[1, 2, 3, 4, 5]


In [6]:
#scenario 5
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7])
total_sum = np.sum(array)
print(total_sum)


28


In [7]:
#scenario 6
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
max_values = np.max(array, axis=0)# Find the maximum value in each column
print(max_values)


[7 8 9]


In [19]:
#scenario 7
import pandas as pd
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'David'],
                   'Age': [25, 30, 22, 35]})         # Create a DataFrame
sorted_df = df.sort_values(by='Age')
print(sorted_df)


      Name  Age
2  Charlie   22
0    Alice   25
1      Bob   30
3    David   35


In [23]:
#scenario 8
df = pd.DataFrame({'Product': ['A', 'B', 'C'], 'Sales': [100, 200, 150]})
total_sales = df['Sales'].sum()
print(total_sales)


450


In [21]:
#scenario 9
x = 10
type(x)

int

In [35]:
#scenario 11


[1, 2, 3, 4, 5]


In [49]:
#scenario 12
sentence = "Hello world"
words = sentence.split()
reversed_words = [word[::-1] for word in words]
reversed_sentence = ' '.join(reversed_words)
print(reversed_sentence)


olleH dlrow


In [41]:
#scenario 13
keys = ['a', 'b', 'c']
values = [1, 2, 3]
combined_dict = dict(zip(keys, values))
print(combined_dict)



{'a': 1, 'b': 2, 'c': 3}


In [47]:
#scenario 14
people = [('Alice', 30), ('Bob', 25), ('Charlie', 35)]
sorted_people = sorted(people, key=lambda x: x[1])
print(sorted_people)


[('Bob', 25), ('Alice', 30), ('Charlie', 35)]


In [53]:
#scenario 15
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mean_values = np.mean(array, axis=1)
print(mean_values)

[2. 5. 8.]


In [57]:
#scenario 16
array = np.zeros(10)
array[4] = 5
print(array)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


In [59]:
#scenario 17
df = pd.DataFrame({'Scores': [85, 90, 78, 92, 88]})
median_score = df['Scores'].median()
print(median_score)

88.0


In [65]:
#scenario 18
df = pd.DataFrame({'Sales': [150, 80, 120], 'Date': ['2024-01-01', '2024-02-01', '2024-03-01']})
filtered_sorted_df = df[df['Sales'] > 100].sort_values(by='Date', ascending=False)
print(filtered_sorted_df)

   Sales        Date
2    120  2024-03-01
0    150  2024-01-01


In [67]:
#scenario 19
def safe_convert_to_int(s):
    try:
        return int(s)
    except ValueError:
        return None

number = safe_convert_to_int("42")
print(number)

42


In [69]:
#scenario 20
data = [1, 'apple', 3.14, 'banana', 42]
strings = [item for item in data if isinstance(item, str)]
print(strings)

['apple', 'banana']
